playlist_task:
  description: >
    Visit the youtube playlist at url {playlist_url} and find all the youtube video URLs
    contained within the playlist.
  expected_output: >
    A text list of video URLs from the playlist at {playlist_url}.
  agent: playlist_parser

video_transcript_task:
  description: >
    Given a set of Youtube video urls, visit each video and extract the text transcript. Don't do any analysis on the transcript.
  expected_output: >
    The raw text transcript as plain text.
  agent: video_transcript

transcript_summarizer_task:
  description: >
    Given a text transcript from a video and generate a summary of the transcript.
    Use bullet points, about 10-15 to summarize each transcript, starting with the title.
  expected_output: >
    A short bullet text summary of the transcript.
  agent: transcript_summarizer